apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: fixa
  labels:
    app: nginx
    version: "1.27.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fixa
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32700
  selector:
    app: nginx