apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to Nginx!</title>
      </head>
      <body>
        <h1>Hello K8s!</h1>
        <p>This is a simple HTML page served by Nginx on Kubernetes.</p>
      </body>
    </html>