apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
    
      # Security headers
      add_header X-Frame-Options "DENY" always;
      add_header Content-Security-Policy "default-src 'self'; script-src 'self'; frame-ancestors 'none';" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
      add_header Access-Control-Allow-Origin "fixa24.com" always;
    
      server {
        listen 80;

        location / {
            # Add custom headers
            add_header X-Custom-Header "MyValue";
            proxy_pass http://your_backend_service;  # Replace with your backend service
        }
      }
    }