apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fixa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: security
        app.kubernetes.io/version: "26.1.2"
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:26.1.2
          envFrom:
            - configMapRef:
                name: keycloak-configmap
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: common
spec:
  selector:
    app.kubernetes.io/name: keycloak
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30990